// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLrRYRYPQ0MK2zIFp03JLFdqchxJpSf0c',
    appId: '1:269517501536:web:ed8b0a13d779db042aff05',
    messagingSenderId: '269517501536',
    projectId: 'ecommapp-33de5',
    authDomain: 'ecommapp-33de5.firebaseapp.com',
    storageBucket: 'ecommapp-33de5.appspot.com',
    measurementId: 'G-NPZKV2JWT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2xyqQDD7TxLB65c80p1g72C7ji9C-4CI',
    appId: '1:269517501536:android:1d591bc67794f2b92aff05',
    messagingSenderId: '269517501536',
    projectId: 'ecommapp-33de5',
    storageBucket: 'ecommapp-33de5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2AWLRIPOgSJVOrjKXP3L9eNqK0XnYlOU',
    appId: '1:269517501536:ios:12f2c2383f9a78d02aff05',
    messagingSenderId: '269517501536',
    projectId: 'ecommapp-33de5',
    storageBucket: 'ecommapp-33de5.appspot.com',
    iosBundleId: 'com.example.ecommapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2AWLRIPOgSJVOrjKXP3L9eNqK0XnYlOU',
    appId: '1:269517501536:ios:12f2c2383f9a78d02aff05',
    messagingSenderId: '269517501536',
    projectId: 'ecommapp-33de5',
    storageBucket: 'ecommapp-33de5.appspot.com',
    iosBundleId: 'com.example.ecommapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLrRYRYPQ0MK2zIFp03JLFdqchxJpSf0c',
    appId: '1:269517501536:web:5296b9c82da8499d2aff05',
    messagingSenderId: '269517501536',
    projectId: 'ecommapp-33de5',
    authDomain: 'ecommapp-33de5.firebaseapp.com',
    storageBucket: 'ecommapp-33de5.appspot.com',
    measurementId: 'G-R876Z1ZKY4',
  );
}
